completed object manipulation 3
jayhpark99/c1021-code-solutions pull request #71
Opened 2021-11-04 23:35 UTC by jayhpark99

![Kapture 2021-11-04 at 16 33 59](https://user-images.githubusercontent.com/90732703/140434549-1787b862-b870-4a9f-a7a9-197a5766da12.gif)

2021-11-16 17:47 UTC, codingcodymiller requested changes

2021-11-16 17:47 UTC, codingcodymiller commented on object-manipulation-3/main.js
> +p4.hand.push(deck[6], deck[7]);
You should do this with a loop over the players, where you add two cards to each of their hands. Also, make sure you removed the cards from the deck once they are given to a player.

2021-11-16 17:47 UTC, codingcodymiller commented on object-manipulation-3/main.js
> +}
This should be doable with loops too

2021-11-22 23:29 UTC, thebearingedge requested changes

2021-11-22 23:29 UTC, thebearingedge commented on object-manipulation-3/main.js
>  var scoreArray = [p1Score, p2Score, p3Score, p4Score];
Try doing this without declaring variables for each separate score.

2021-11-23 00:08 UTC, thebearingedge approved these changes

2021-11-23 00:36 UTC, merged